"use server";

import { db } from "@/lib/db";
import {
  goals,
  goalMilestones,
  goalReflections,
  projects,
  sprints,
  tasks,
  subtasks,
  learningTopics,
  learningResources,
  studySessions,
  problems,
  problemAttempts,
  workoutRoutines,
  exercises,
  routineExercises,
  workoutSessions,
  workoutSets,
  financialAccounts,
  transactions,
  upcomingCashflows,
  wishlistItems,
  notes,
} from "@/lib/db/schema";

export async function exportAllDataAction() {
  const [
    allGoals,
    allGoalMilestones,
    allGoalReflections,
    allProjects,
    allSprints,
    allTasks,
    allSubtasks,
    allLearningTopics,
    allLearningResources,
    allStudySessions,
    allProblems,
    allProblemAttempts,
    allWorkoutRoutines,
    allExercises,
    allRoutineExercises,
    allWorkoutSessions,
    allWorkoutSets,
    allAccounts,
    allTransactions,
    allUpcomingCashflows,
    allWishlist,
    allNotes,
  ] = await Promise.all([
    db.select().from(goals),
    db.select().from(goalMilestones),
    db.select().from(goalReflections),
    db.select().from(projects),
    db.select().from(sprints),
    db.select().from(tasks),
    db.select().from(subtasks),
    db.select().from(learningTopics),
    db.select().from(learningResources),
    db.select().from(studySessions),
    db.select().from(problems),
    db.select().from(problemAttempts),
    db.select().from(workoutRoutines),
    db.select().from(exercises),
    db.select().from(routineExercises),
    db.select().from(workoutSessions),
    db.select().from(workoutSets),
    db.select().from(financialAccounts),
    db.select().from(transactions),
    db.select().from(upcomingCashflows),
    db.select().from(wishlistItems),
    db.select().from(notes),
  ]);

  const exportPayload = {
    metadata: {
      exportedAt: new Date().toISOString(),
      system: "MOSHA V2 Personal Operating System",
      version: "2.0.0",
    },
    data: {
      goals: allGoals,
      goalMilestones: allGoalMilestones,
      goalReflections: allGoalReflections,
      projects: allProjects,
      sprints: allSprints,
      tasks: allTasks,
      subtasks: allSubtasks,
      learningTopics: allLearningTopics,
      learningResources: allLearningResources,
      studySessions: allStudySessions,
      problems: allProblems,
      problemAttempts: allProblemAttempts,
      workoutRoutines: allWorkoutRoutines,
      exercises: allExercises,
      routineExercises: allRoutineExercises,
      workoutSessions: allWorkoutSessions,
      workoutSets: allWorkoutSets,
      financialAccounts: allAccounts,
      transactions: allTransactions,
      upcomingCashflows: allUpcomingCashflows,
      wishlistItems: allWishlist,
      notes: allNotes,
    },
    counts: {
      goals: allGoals.length,
      projects: allProjects.length,
      tasks: allTasks.length,
      learningTopics: allLearningTopics.length,
      studySessions: allStudySessions.length,
      problems: allProblems.length,
      problemAttempts: allProblemAttempts.length,
      workoutSessions: allWorkoutSessions.length,
      workoutSets: allWorkoutSets.length,
      transactions: allTransactions.length,
      notes: allNotes.length,
    },
  };

  return exportPayload;
}
